### PR TITLE
Main webpage

### PR DESCRIPTION
**Pull request by ferbaco86**
- This project is a clone of the Newsweek Magazine website (https://www.newsweek.com) utilizing Bootstrap as the main component for structuring the webpage.
- This Main-Webpage branch consist of the first working version of the project

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @ferbaco86 
### Good you have done :clap: However, you have a few changes to make before your project could be approved.
- Add a logo to fix your navigation on responsive devices
logo missing
remove the image
responsive screen
- On responsive devices, remove the inner scroll 
remove scroll on resposive
### Make these changes and resubmit for another code review. Good luck.
- For more clarification, contact me on slack @iamraymond
- Happy coding!

**Comment by ferbaco86** [comment]
The logos appear correctly on live versions. It was a problem with the URL path of the elements not pointing out directly to the local file. It has been fixed. 
Thanks for the comments!

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  @ferbaco86  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

However, consider making these change👇
 - [ ] Required - Kindly ensure you make your navbar float, as seen in the original webpage.

I trust you will make this change before merging.

Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
